spring.application.name=PRISMA-Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/PRISMA
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prisma.reset@gmail.com
spring.mail.password=kiysnwrfiviwljdf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
