spring.application.name=PRISMA-Backend
spring.datasource.url=jdbc:postgresql://cd7f19r8oktbkp.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d440bsd3dnvd5i?sslmode=require&prepareThreshold=0
spring.datasource.username=udlbpq8npqkp1i
spring.datasource.password=pebbd11d16eb70ac3600c8d01e67231c21056dc29ae143067b990687c48ce3b0a
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
